@startuml
title Высокоуровневое представление системы

component edupra_game_client
component edupra_game_server
component gym_backgammon
component edupra_model_server
component edupra_model_builder
component edupra_model_evaluator
component edupra_core

edupra_game_server <-- edupra_game_client
gym_backgammon  <-- edupra_game_server
edupra_model_server  <-- edupra_game_server

gym_backgammon  <-- edupra_core
edupra_core  <-- edupra_model_server
edupra_core  <-- edupra_model_builder

edupra_core  <-- edupra_model_evaluator
@enduml
